[workspace]
name = "DANPOS3"
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64", "osx-64"]
authors = ["Kaifu Chen", "Samantha Klasfeld", "Boen Chen <boenc28@gmail.com>"]
description = "A toolkit for Dynamic Analysis of Nucleosome and Protein Occupancy by Sequencing"
license = "GPL-3.0-or-later"
license-file = "LICENSE"
readme = "README.md"
homepage = "https://sites.google.com/site/danposdoc/home"
repository = "https://github.com/sklasfeld/DANPOS3"
documentation = "https://sites.google.com/site/danposdoc/b-documentation"
preview = ["pixi-build"]

[tasks]

[package]
name = "DANPOS3"
version = "3.0.1"
authors = ["Kaifu Chen", "Samantha Klasfeld", "Boen Chen <boenc28@gmail.com>"]
description = "A toolkit for Dynamic Analysis of Nucleosome and Protein Occupancy by Sequencing"
license = "GPL-3.0-or-later"
license-file = "LICENSE"
readme = "README.md"
homepage = "https://sites.google.com/site/danposdoc/home"
repository = "https://github.com/sklasfeld/DANPOS3"
documentation = "https://sites.google.com/site/danposdoc/b-documentation"

[package.build]
backend = { name = "pixi-build-python", version = "*", channels = [  "https://prefix.dev/pixi-build-backends",  "https://prefix.dev/conda-forge"] }

[dependencies]
python = "3.7.6.*"
r-base = "4.0.1.*"
samtools = "1.7.*"
numpy = "1.18.5.*"
pysam = "0.16.0.1.*"
rpy2 = "3.3.*"

[package.build-dependencies]
python = "3.7.6.*"
setuptools = "*"
wheel = "*"

[package.host-dependencies]
python = "3.7.6*"
setuptools = "*"
wheel = "*"