[project]
name = "DANPOS3"
version = "3.0.1"
dependencies = []

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"danpos" = "."}
packages = ["danpos"]